version: '3.8'

services:
  web:
    build: ./todo-project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./todo-project:/usr/src/app
    ports:
      - 8003:8000
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
